---
- name: Install Pakages
  hosts: all
  become: yes

  tasks:
    - name: Installing apache
      yum:
        name: httpd
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Installing apache
      apt:
        name: httpd
        state: absent
      when: ansible_os_family == "Debian"
